//The Fibonacci Series is a mathematical series that starts with 0 and 1 and is generated by adding the two preceding numbers to generate the next one

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

int main() {
    int i,n,a=0,b=1,c=0;
    scanf("%d",&n);
for (i = 1; i <= n; i++) 
{
printf("%d ", c);
    a=b;
    b=c;
    c=a+b;
        }
return 0;
}
